//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace careforever {
    
    
    public partial class Login {
        
        /// <summary>
        /// panel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panel;
        
        /// <summary>
        /// btnRegister control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnRegister;
        
        /// <summary>
        /// txtemail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtemail;
        
        /// <summary>
        /// RFVtxtemail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RFVtxtemail;
        
        /// <summary>
        /// FilteredTextBoxExtender6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender FilteredTextBoxExtender6;
        
        /// <summary>
        /// txtpassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtpassword;
        
        /// <summary>
        /// RFVtxtpassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RFVtxtpassword;
        
        /// <summary>
        /// lblError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblError;
        
        /// <summary>
        /// btnsignin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnsignin;
        
        /// <summary>
        /// lnkforgotpwd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkforgotpwd;
        
        /// <summary>
        /// btnPopUp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnPopUp;
        
        /// <summary>
        /// Orders_ModelPopUp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ModalPopupExtender Orders_ModelPopUp;
        
        /// <summary>
        /// OrdersPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel OrdersPanel;
        
        /// <summary>
        /// textname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label textname;
        
        /// <summary>
        /// txtages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label txtages;
        
        /// <summary>
        /// textaddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label textaddress;
        
        /// <summary>
        /// lbldate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbldate;
        
        /// <summary>
        /// BtnOK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtnOK;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new careforever.MasterPageNew Master {
            get {
                return ((careforever.MasterPageNew)(base.Master));
            }
        }
    }
}
